[project]
name = "learn-cdktf-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cdktf>=0.20.11",
    "cdktf-cdktf-provider-aws>=19.57.0",
    "cdktf-cdktf-provider-docker>=11.0.0",
    "pytest>=8.3.5",
]
